### Site Settings ###
title               : Visanu Wanchai
description         : >-                               # >- means to ignore newlines until "url:"
                      I compare nearly billions of 
                      protein sequences to find meaning 
                      in life and something useful for human health. 

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : visanuwan/visanuwan.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Visanu Wanchai
  image             : https://bit.ly/31jdFG4
  # behance           : your_username
# dribbble          : your_username
  email             : visanuw86@gmail.com
  facebook          : visanu.wanchai
  github            : visanuwan
# gitlab            : your_username
  instagram         : visanuwan
  # linkedin          : your_username
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : VisanuLive
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock